Attach database to project   attach h2 db
mrchernova/trucking_v2 pull request #1
Opened 2022-12-22 11:24 UTC by mrchernova

2022-12-23 20:13 UTC, RomanKashenok approved these changes
good. just a few comments )

2022-12-23 20:13 UTC, RomanKashenok commented on pom.xml
> +<!--		</dependency>-->
Убери это пока - у нас есть отдельная таска на секьюрити

2022-12-23 20:13 UTC, RomanKashenok commented on src/main/java/by/project/trucking_v2/controller/indexController.java
> +public class indexController {
Зачем тебе сейчас контроллер? Давай для этого дела тесты добавим :)

2022-12-23 20:13 UTC, RomanKashenok commented on src/main/resources/db_trucking_20221013.sql
> +CREATE TABLE `organizations` (
maybe carriers?

2022-12-23 20:24 UTC, RomanKashenok requested changes

2022-12-23 20:24 UTC, RomanKashenok commented on src/main/resources/db_trucking_20221013.sql
> +  `transport_id` int DEFAULT NULL,
I think one organization could have many transports

2022-12-23 20:24 UTC, RomanKashenok commented on src/main/resources/db_trucking_20221013.sql
> +  `role_id` int NOT NULL,
I don't see table roles

2022-12-23 20:24 UTC, RomanKashenok commented on src/main/resources/db_trucking_20221013.sql
> +  `status_id` int NOT NULL,
I don't see relations between transport and driver

2022-12-23 20:41 UTC, mrchernova commented on src/main/resources/db_trucking_20221013.sql
> +  `role_id` int NOT NULL,
roles in enum

2022-12-25 12:16 UTC, mrchernova commented on src/main/resources/db_trucking_20221013.sql
> +  `status_id` int NOT NULL,
Связь через таблицу Carriers (бывшая Organizations). У каждого водителя есть поле carriers_id - ссылка на организацию перевозчика. И у таблицы Transports тоже есть такое поле. 
Итого у нас есть связь между водителем и машиной через таблицу Carriers

2022-12-25 12:23 UTC, mrchernova commented on src/main/resources/db_trucking_20221013.sql
> +  `status_id` int NOT NULL,
А и если перевозчик имеет по несколько водителей и машин, то информация кто именно принял заказ и на какой машине его перевозил, будет храниться в таблице orders_base

2022-12-27 07:43 UTC, RomanKashenok approved these changes
Только давай переименуем orders_base в completed_orders.

2022-12-27 07:43 UTC, RomanKashenok commented on src/main/java/by/project/trucking_v2/controller/indexController.java
> +public class indexController {
Сдклай его хотя бы с заглавной буквы, раз не хочешь так убирать

2022-12-27 07:43 UTC, RomanKashenok commented on src/main/java/by/project/trucking_v2/service/UserService.java
> +        return userRepository.findById(id).orElse(null);
orElseThrow, а не null

2022-12-27 12:53 UTC, merged