Rest controllers for crud (table users)
mrchernova/trucking_v2 pull request #3
Opened 2023-01-03 15:43 UTC by mrchernova

2023-01-04 14:49 UTC, RomanKashenok requested changes

2023-01-04 14:49 UTC, RomanKashenok commented on pom.xml
> +<!--		</dependency>-->
это нам не понадобится )) убирай

2023-01-04 14:49 UTC, RomanKashenok commented on src/main/java/by/project/trucking_v2/controller/UserRESTController.java
> +    @GetMapping("/users")
Обнови маппинги как договаривались

2023-01-04 14:49 UTC, RomanKashenok commented on src/main/java/by/project/trucking_v2/repository/UserRepository.java
> +    User getUserById(int id);
есть же такой метод в самом круд репозитории

2023-01-04 21:03 UTC, mrchernova commented on src/main/java/by/project/trucking_v2/controller/UserRESTController.java
> +    @GetMapping("/users")
+

2023-01-04 21:03 UTC, mrchernova commented on pom.xml
> +<!--		</dependency>-->
+

2023-01-04 21:03 UTC, mrchernova commented on src/main/java/by/project/trucking_v2/repository/UserRepository.java
> +    User getUserById(int id);
+

2023-01-10 16:18 UTC, RomanKashenok approved these changes
Поправь пару замечаний и можно мержить

2023-01-10 16:18 UTC, RomanKashenok commented on src/main/java/by/project/trucking_v2/service/UserService.java
> +    User update(int id, User user);
тут не нужен отдельно айди. Ты же уже передаешь существующего юзера - у него внутри айдишка уже дежит

2023-01-10 16:18 UTC, RomanKashenok commented on src/main/java/by/project/trucking_v2/service/UserServiceImpl.java
>          }
Это не нужно - ты строками выше уже обработала случай, когда юзер не найден

2023-01-16 16:43 UTC, merged