Rest controllers + implement service logic
mrchernova/trucking_v2 pull request #4
Opened 2023-01-12 14:14 UTC by mrchernova

2023-01-13 18:31 UTC, RomanKashenok requested changes
Also mark every service method, that update DB state as @Transactional. And read a lil bit about it

2023-01-13 18:31 UTC, RomanKashenok commented on src/main/java/by/project/trucking_v2/controller/CompletedOrderController.java
> +    public CompletedOrder getById(@PathVariable("id") int id) {
Integer

2023-01-13 18:31 UTC, RomanKashenok commented on src/main/java/by/project/trucking_v2/controller/DriverController.java
> +    public Driver create(@RequestBody Driver driver, @RequestParam int le_id) {
le_id? what's that?

2023-01-13 18:31 UTC, RomanKashenok commented on src/main/java/by/project/trucking_v2/controller/DriverController.java
> +    public Driver create(@RequestBody Driver driver, @RequestParam int le_id) {
add it to body. in body paste driver and legal entity id (or whole legal entity)

2023-01-13 18:31 UTC, RomanKashenok commented on src/main/java/by/project/trucking_v2/controller/LegalEntityController.java
> +    public LegalEntity update(@PathVariable("id") int id, @RequestBody LegalEntity legalEntity) {
remove pah variable

2023-01-13 18:31 UTC, RomanKashenok commented on src/main/java/by/project/trucking_v2/controller/OrderController.java
> +    public Order create(@RequestBody Order order, @RequestParam int le_id) {
same as with Driver

2023-01-13 18:31 UTC, RomanKashenok commented on src/main/java/by/project/trucking_v2/controller/OrderController.java
> +    public Order update(@PathVariable("id") int id, @RequestBody Order order) {
same as with Driver

2023-01-13 18:31 UTC, RomanKashenok commented on src/main/java/by/project/trucking_v2/controller/OrderController.java
> +    public Order orderChoice(@PathVariable("id") int id, @RequestBody Order order) {
the same

2023-01-13 18:31 UTC, RomanKashenok commented on src/main/java/by/project/trucking_v2/controller/TransportController.java
> +    public Transport create(@RequestBody Transport transport, @RequestParam int le_id) {
same

2023-01-13 18:31 UTC, RomanKashenok commented on src/main/java/by/project/trucking_v2/controller/TransportController.java
> +    public Transport update(@PathVariable("id") int id, @RequestBody Transport transport) {
same

2023-01-13 18:31 UTC, RomanKashenok commented on src/main/java/by/project/trucking_v2/controller/UserController.java
> +    public User updateUser(@PathVariable("id") int id, @RequestBody User user) {
same

2023-01-13 18:31 UTC, RomanKashenok commented on src/main/java/by/project/trucking_v2/exception/NotFoundException.java
> +        logger.severe("404. Such id not found");
remove all logic from constructor

2023-01-13 18:31 UTC, RomanKashenok commented on src/main/java/by/project/trucking_v2/repository/UserRepository.java
> -@Repository
why do you removed it?

2023-01-13 18:31 UTC, RomanKashenok commented on src/main/java/by/project/trucking_v2/service/CompletedOrderServiceImpl.java
> +    public static final String ANSI_RESET = "\u001B[0m";
let's not use such beautification.. just forget about it

2023-01-13 18:31 UTC, RomanKashenok commented on src/main/java/by/project/trucking_v2/service/CompletedOrderServiceImpl.java
> +    CompletedOrderRepository completedOrderRepository;
why not private as others?

2023-01-13 18:31 UTC, RomanKashenok commented on src/main/java/by/project/trucking_v2/service/CompletedOrderServiceImpl.java
> +    public CompletedOrder orderInProgress(int id_order) {
orderId

2023-01-13 18:31 UTC, RomanKashenok commented on src/main/java/by/project/trucking_v2/service/CompletedOrderServiceImpl.java
> +        /*это будет передаваться* через форму*/
ничего не понятно, но очень интересно )) завтра расскажешь

2023-01-13 18:31 UTC, RomanKashenok commented on src/main/java/by/project/trucking_v2/service/OrderServiceImpl.java
> +        newOrder.setLegalEntity(le);
and how differs order and newOrder? Maybe let's save just 'order'

2023-01-13 18:31 UTC, RomanKashenok commented on src/main/java/by/project/trucking_v2/service/TransportServiceImpl.java
> +    public Transport save(Transport transport, int le_id) {
same as with order

2023-01-14 06:55 UTC, mrchernova commented on src/main/java/by/project/trucking_v2/repository/UserRepository.java
> -@Repository
случайно

2023-01-14 07:22 UTC, mrchernova commented on src/main/java/by/project/trucking_v2/controller/LegalEntityController.java
> +    public LegalEntity update(@PathVariable("id") int id, @RequestBody LegalEntity legalEntity) {
А как мы тогда сможем менять LegalEntity?

2023-01-16 14:53 UTC, RomanKashenok approved these changes

2023-01-16 14:53 UTC, RomanKashenok commented on src/main/java/by/project/trucking_v2/controller/DriverController.java
> +    public Driver update(@PathVariable Integer id, @RequestBody Driver driver) {
Ок. Но я не понимаю зачем тут айдишник отдельно

2023-01-16 16:43 UTC, merged